name: CI Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run go tests
        run: go test ./...
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          custom_release_rules: "break:major,feat:minor,fix:patch"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ github.event.repository.name }}
          tags: latest, ${{ steps.tag_version.outputs.new_tag }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
